// Key generated for a wallet on registration.
defaultKeyConfig: {
    backend: jwk
    keyType: Ed25519
}

// DID generated (based on the above key) for a wallet on registration.
defaultDidConfig: {
    method: jwk
}
