/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.dcs.sis.domain.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Device information for registration */
@org.apache.avro.specific.AvroGenerated
public class DeviceInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4049571217263507793L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceInfo\",\"namespace\":\"com.example.dcs.sis.domain.avro\",\"doc\":\"Device information for registration\",\"fields\":[{\"name\":\"deviceModel\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Device model information\",\"default\":null},{\"name\":\"osVersion\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Operating system version\",\"default\":null},{\"name\":\"deviceId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Unique device identifier\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device model information */
  private java.lang.String deviceModel;
  /** Operating system version */
  private java.lang.String osVersion;
  /** Unique device identifier */
  private java.lang.String deviceId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceInfo() {}

  /**
   * All-args constructor.
   * @param deviceModel Device model information
   * @param osVersion Operating system version
   * @param deviceId Unique device identifier
   */
  public DeviceInfo(java.lang.String deviceModel, java.lang.String osVersion, java.lang.String deviceId) {
    this.deviceModel = deviceModel;
    this.osVersion = osVersion;
    this.deviceId = deviceId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceModel;
    case 1: return osVersion;
    case 2: return deviceId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceModel = value$ != null ? value$.toString() : null; break;
    case 1: osVersion = value$ != null ? value$.toString() : null; break;
    case 2: deviceId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceModel' field.
   * @return Device model information
   */
  public java.lang.String getDeviceModel() {
    return deviceModel;
  }


  /**
   * Sets the value of the 'deviceModel' field.
   * Device model information
   * @param value the value to set.
   */
  public void setDeviceModel(java.lang.String value) {
    this.deviceModel = value;
  }

  /**
   * Gets the value of the 'osVersion' field.
   * @return Operating system version
   */
  public java.lang.String getOsVersion() {
    return osVersion;
  }


  /**
   * Sets the value of the 'osVersion' field.
   * Operating system version
   * @param value the value to set.
   */
  public void setOsVersion(java.lang.String value) {
    this.osVersion = value;
  }

  /**
   * Gets the value of the 'deviceId' field.
   * @return Unique device identifier
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }


  /**
   * Sets the value of the 'deviceId' field.
   * Unique device identifier
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.deviceId = value;
  }

  /**
   * Creates a new DeviceInfo RecordBuilder.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.DeviceInfo.Builder newBuilder() {
    return new com.example.dcs.sis.domain.avro.DeviceInfo.Builder();
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.DeviceInfo.Builder newBuilder(com.example.dcs.sis.domain.avro.DeviceInfo.Builder other) {
    if (other == null) {
      return new com.example.dcs.sis.domain.avro.DeviceInfo.Builder();
    } else {
      return new com.example.dcs.sis.domain.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing DeviceInfo instance.
   * @param other The existing instance to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.DeviceInfo.Builder newBuilder(com.example.dcs.sis.domain.avro.DeviceInfo other) {
    if (other == null) {
      return new com.example.dcs.sis.domain.avro.DeviceInfo.Builder();
    } else {
      return new com.example.dcs.sis.domain.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceInfo>
    implements org.apache.avro.data.RecordBuilder<DeviceInfo> {

    /** Device model information */
    private java.lang.String deviceModel;
    /** Operating system version */
    private java.lang.String osVersion;
    /** Unique device identifier */
    private java.lang.String deviceId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.dcs.sis.domain.avro.DeviceInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceModel)) {
        this.deviceModel = data().deepCopy(fields()[0].schema(), other.deviceModel);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[1].schema(), other.osVersion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[2].schema(), other.deviceId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.dcs.sis.domain.avro.DeviceInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deviceModel)) {
        this.deviceModel = data().deepCopy(fields()[0].schema(), other.deviceModel);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[1].schema(), other.osVersion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[2].schema(), other.deviceId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'deviceModel' field.
      * Device model information
      * @return The value.
      */
    public java.lang.String getDeviceModel() {
      return deviceModel;
    }


    /**
      * Sets the value of the 'deviceModel' field.
      * Device model information
      * @param value The value of 'deviceModel'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder setDeviceModel(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceModel = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceModel' field has been set.
      * Device model information
      * @return True if the 'deviceModel' field has been set, false otherwise.
      */
    public boolean hasDeviceModel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceModel' field.
      * Device model information
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder clearDeviceModel() {
      deviceModel = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'osVersion' field.
      * Operating system version
      * @return The value.
      */
    public java.lang.String getOsVersion() {
      return osVersion;
    }


    /**
      * Sets the value of the 'osVersion' field.
      * Operating system version
      * @param value The value of 'osVersion'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder setOsVersion(java.lang.String value) {
      validate(fields()[1], value);
      this.osVersion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'osVersion' field has been set.
      * Operating system version
      * @return True if the 'osVersion' field has been set, false otherwise.
      */
    public boolean hasOsVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'osVersion' field.
      * Operating system version
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder clearOsVersion() {
      osVersion = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceId' field.
      * Unique device identifier
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return deviceId;
    }


    /**
      * Sets the value of the 'deviceId' field.
      * Unique device identifier
      * @param value The value of 'deviceId'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder setDeviceId(java.lang.String value) {
      validate(fields()[2], value);
      this.deviceId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceId' field has been set.
      * Unique device identifier
      * @return True if the 'deviceId' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'deviceId' field.
      * Unique device identifier
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.DeviceInfo.Builder clearDeviceId() {
      deviceId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceInfo build() {
      try {
        DeviceInfo record = new DeviceInfo();
        record.deviceModel = fieldSetFlags()[0] ? this.deviceModel : (java.lang.String) defaultValue(fields()[0]);
        record.osVersion = fieldSetFlags()[1] ? this.osVersion : (java.lang.String) defaultValue(fields()[1]);
        record.deviceId = fieldSetFlags()[2] ? this.deviceId : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceInfo>
    READER$ = (org.apache.avro.io.DatumReader<DeviceInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.deviceModel == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceModel);
    }

    if (this.osVersion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.osVersion);
    }

    if (this.deviceId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceId);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceModel = null;
      } else {
        this.deviceModel = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.osVersion = null;
      } else {
        this.osVersion = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceId = null;
      } else {
        this.deviceId = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceModel = null;
          } else {
            this.deviceModel = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.osVersion = null;
          } else {
            this.osVersion = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceId = null;
          } else {
            this.deviceId = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (deviceModel == null ? 0 : deviceModel.hashCode());
    result = 31 * result + (osVersion == null ? 0 : osVersion.hashCode());
    result = 31 * result + (deviceId == null ? 0 : deviceId.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof DeviceInfo)) {
      return false;
    }
    DeviceInfo other = (DeviceInfo) o;
    if (!java.util.Objects.equals(this.deviceModel, other.deviceModel)) {
      return false;
    }
    if (!java.util.Objects.equals(this.osVersion, other.osVersion)) {
      return false;
    }
    if (!java.util.Objects.equals(this.deviceId, other.deviceId)) {
      return false;
    }
    return true;
  }
}










