/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.dcs.sis.domain.avro;
/** Supported language codes */
@org.apache.avro.specific.AvroGenerated
public enum LanguageCode implements org.apache.avro.generic.GenericEnumSymbol<LanguageCode> {
  PT, EN, ES, FR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LanguageCode\",\"namespace\":\"com.example.dcs.sis.domain.avro\",\"doc\":\"Supported language codes\",\"symbols\":[\"PT\",\"EN\",\"ES\",\"FR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
