/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.dcs.sis.domain.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Course information for the student */
@org.apache.avro.specific.AvroGenerated
public class CourseInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1266173308192417704L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CourseInfo\",\"namespace\":\"com.example.dcs.sis.domain.avro\",\"doc\":\"Course information for the student\",\"fields\":[{\"name\":\"courseCode\",\"type\":\"int\",\"doc\":\"Course code identifier\"},{\"name\":\"courseName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Course name\"},{\"name\":\"degreeCode\",\"type\":[\"null\",\"int\"],\"doc\":\"Degree code (optional)\",\"default\":null},{\"name\":\"degreeName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Degree name (optional)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CourseInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CourseInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CourseInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CourseInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CourseInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CourseInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CourseInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CourseInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CourseInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Course code identifier */
  private int courseCode;
  /** Course name */
  private java.lang.String courseName;
  /** Degree code (optional) */
  private java.lang.Integer degreeCode;
  /** Degree name (optional) */
  private java.lang.String degreeName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CourseInfo() {}

  /**
   * All-args constructor.
   * @param courseCode Course code identifier
   * @param courseName Course name
   * @param degreeCode Degree code (optional)
   * @param degreeName Degree name (optional)
   */
  public CourseInfo(java.lang.Integer courseCode, java.lang.String courseName, java.lang.Integer degreeCode, java.lang.String degreeName) {
    this.courseCode = courseCode;
    this.courseName = courseName;
    this.degreeCode = degreeCode;
    this.degreeName = degreeName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return courseCode;
    case 1: return courseName;
    case 2: return degreeCode;
    case 3: return degreeName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: courseCode = (java.lang.Integer)value$; break;
    case 1: courseName = value$ != null ? value$.toString() : null; break;
    case 2: degreeCode = (java.lang.Integer)value$; break;
    case 3: degreeName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'courseCode' field.
   * @return Course code identifier
   */
  public int getCourseCode() {
    return courseCode;
  }


  /**
   * Sets the value of the 'courseCode' field.
   * Course code identifier
   * @param value the value to set.
   */
  public void setCourseCode(int value) {
    this.courseCode = value;
  }

  /**
   * Gets the value of the 'courseName' field.
   * @return Course name
   */
  public java.lang.String getCourseName() {
    return courseName;
  }


  /**
   * Sets the value of the 'courseName' field.
   * Course name
   * @param value the value to set.
   */
  public void setCourseName(java.lang.String value) {
    this.courseName = value;
  }

  /**
   * Gets the value of the 'degreeCode' field.
   * @return Degree code (optional)
   */
  public java.lang.Integer getDegreeCode() {
    return degreeCode;
  }


  /**
   * Sets the value of the 'degreeCode' field.
   * Degree code (optional)
   * @param value the value to set.
   */
  public void setDegreeCode(java.lang.Integer value) {
    this.degreeCode = value;
  }

  /**
   * Gets the value of the 'degreeName' field.
   * @return Degree name (optional)
   */
  public java.lang.String getDegreeName() {
    return degreeName;
  }


  /**
   * Sets the value of the 'degreeName' field.
   * Degree name (optional)
   * @param value the value to set.
   */
  public void setDegreeName(java.lang.String value) {
    this.degreeName = value;
  }

  /**
   * Creates a new CourseInfo RecordBuilder.
   * @return A new CourseInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.CourseInfo.Builder newBuilder() {
    return new com.example.dcs.sis.domain.avro.CourseInfo.Builder();
  }

  /**
   * Creates a new CourseInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CourseInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.CourseInfo.Builder newBuilder(com.example.dcs.sis.domain.avro.CourseInfo.Builder other) {
    if (other == null) {
      return new com.example.dcs.sis.domain.avro.CourseInfo.Builder();
    } else {
      return new com.example.dcs.sis.domain.avro.CourseInfo.Builder(other);
    }
  }

  /**
   * Creates a new CourseInfo RecordBuilder by copying an existing CourseInfo instance.
   * @param other The existing instance to copy.
   * @return A new CourseInfo RecordBuilder
   */
  public static com.example.dcs.sis.domain.avro.CourseInfo.Builder newBuilder(com.example.dcs.sis.domain.avro.CourseInfo other) {
    if (other == null) {
      return new com.example.dcs.sis.domain.avro.CourseInfo.Builder();
    } else {
      return new com.example.dcs.sis.domain.avro.CourseInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for CourseInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CourseInfo>
    implements org.apache.avro.data.RecordBuilder<CourseInfo> {

    /** Course code identifier */
    private int courseCode;
    /** Course name */
    private java.lang.String courseName;
    /** Degree code (optional) */
    private java.lang.Integer degreeCode;
    /** Degree name (optional) */
    private java.lang.String degreeName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.dcs.sis.domain.avro.CourseInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.courseCode)) {
        this.courseCode = data().deepCopy(fields()[0].schema(), other.courseCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.courseName)) {
        this.courseName = data().deepCopy(fields()[1].schema(), other.courseName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.degreeCode)) {
        this.degreeCode = data().deepCopy(fields()[2].schema(), other.degreeCode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.degreeName)) {
        this.degreeName = data().deepCopy(fields()[3].schema(), other.degreeName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CourseInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.dcs.sis.domain.avro.CourseInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.courseCode)) {
        this.courseCode = data().deepCopy(fields()[0].schema(), other.courseCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.courseName)) {
        this.courseName = data().deepCopy(fields()[1].schema(), other.courseName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.degreeCode)) {
        this.degreeCode = data().deepCopy(fields()[2].schema(), other.degreeCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.degreeName)) {
        this.degreeName = data().deepCopy(fields()[3].schema(), other.degreeName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'courseCode' field.
      * Course code identifier
      * @return The value.
      */
    public int getCourseCode() {
      return courseCode;
    }


    /**
      * Sets the value of the 'courseCode' field.
      * Course code identifier
      * @param value The value of 'courseCode'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder setCourseCode(int value) {
      validate(fields()[0], value);
      this.courseCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'courseCode' field has been set.
      * Course code identifier
      * @return True if the 'courseCode' field has been set, false otherwise.
      */
    public boolean hasCourseCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'courseCode' field.
      * Course code identifier
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder clearCourseCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'courseName' field.
      * Course name
      * @return The value.
      */
    public java.lang.String getCourseName() {
      return courseName;
    }


    /**
      * Sets the value of the 'courseName' field.
      * Course name
      * @param value The value of 'courseName'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder setCourseName(java.lang.String value) {
      validate(fields()[1], value);
      this.courseName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'courseName' field has been set.
      * Course name
      * @return True if the 'courseName' field has been set, false otherwise.
      */
    public boolean hasCourseName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'courseName' field.
      * Course name
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder clearCourseName() {
      courseName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'degreeCode' field.
      * Degree code (optional)
      * @return The value.
      */
    public java.lang.Integer getDegreeCode() {
      return degreeCode;
    }


    /**
      * Sets the value of the 'degreeCode' field.
      * Degree code (optional)
      * @param value The value of 'degreeCode'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder setDegreeCode(java.lang.Integer value) {
      validate(fields()[2], value);
      this.degreeCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'degreeCode' field has been set.
      * Degree code (optional)
      * @return True if the 'degreeCode' field has been set, false otherwise.
      */
    public boolean hasDegreeCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'degreeCode' field.
      * Degree code (optional)
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder clearDegreeCode() {
      degreeCode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'degreeName' field.
      * Degree name (optional)
      * @return The value.
      */
    public java.lang.String getDegreeName() {
      return degreeName;
    }


    /**
      * Sets the value of the 'degreeName' field.
      * Degree name (optional)
      * @param value The value of 'degreeName'.
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder setDegreeName(java.lang.String value) {
      validate(fields()[3], value);
      this.degreeName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'degreeName' field has been set.
      * Degree name (optional)
      * @return True if the 'degreeName' field has been set, false otherwise.
      */
    public boolean hasDegreeName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'degreeName' field.
      * Degree name (optional)
      * @return This builder.
      */
    public com.example.dcs.sis.domain.avro.CourseInfo.Builder clearDegreeName() {
      degreeName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CourseInfo build() {
      try {
        CourseInfo record = new CourseInfo();
        record.courseCode = fieldSetFlags()[0] ? this.courseCode : (java.lang.Integer) defaultValue(fields()[0]);
        record.courseName = fieldSetFlags()[1] ? this.courseName : (java.lang.String) defaultValue(fields()[1]);
        record.degreeCode = fieldSetFlags()[2] ? this.degreeCode : (java.lang.Integer) defaultValue(fields()[2]);
        record.degreeName = fieldSetFlags()[3] ? this.degreeName : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CourseInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<CourseInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CourseInfo>
    READER$ = (org.apache.avro.io.DatumReader<CourseInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.courseCode);

    out.writeString(this.courseName);

    if (this.degreeCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.degreeCode);
    }

    if (this.degreeName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.degreeName);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.courseCode = in.readInt();

      this.courseName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.degreeCode = null;
      } else {
        this.degreeCode = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.degreeName = null;
      } else {
        this.degreeName = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.courseCode = in.readInt();
          break;

        case 1:
          this.courseName = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.degreeCode = null;
          } else {
            this.degreeCode = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.degreeName = null;
          } else {
            this.degreeName = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Integer.hashCode(courseCode);
    result = 31 * result + (courseName == null ? 0 : courseName.hashCode());
    result = 31 * result + (degreeCode == null ? 0 : degreeCode.hashCode());
    result = 31 * result + (degreeName == null ? 0 : degreeName.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof CourseInfo)) {
      return false;
    }
    CourseInfo other = (CourseInfo) o;
    if (this.courseCode != other.courseCode) {
      return false;
    }
    if (!java.util.Objects.equals(this.courseName, other.courseName)) {
      return false;
    }
    if (!java.util.Objects.equals(this.degreeCode, other.degreeCode)) {
      return false;
    }
    if (!java.util.Objects.equals(this.degreeName, other.degreeName)) {
      return false;
    }
    return true;
  }
}










