/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pt.ulusofona.digital.wallet.domain.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Additional client information */
@org.apache.avro.specific.AvroGenerated
public class ClientInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2933702286811115407L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientInfo\",\"namespace\":\"pt.ulusofona.digital.wallet.domain.avro\",\"doc\":\"Additional client information\",\"fields\":[{\"name\":\"deviceModel\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Device model information\",\"default\":null},{\"name\":\"osVersion\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Operating system version\",\"default\":null},{\"name\":\"appVersion\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Application version\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClientInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClientInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClientInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClientInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClientInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClientInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClientInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClientInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClientInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device model information */
  private java.lang.String deviceModel;
  /** Operating system version */
  private java.lang.String osVersion;
  /** Application version */
  private java.lang.String appVersion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClientInfo() {}

  /**
   * All-args constructor.
   * @param deviceModel Device model information
   * @param osVersion Operating system version
   * @param appVersion Application version
   */
  public ClientInfo(java.lang.String deviceModel, java.lang.String osVersion, java.lang.String appVersion) {
    this.deviceModel = deviceModel;
    this.osVersion = osVersion;
    this.appVersion = appVersion;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceModel;
    case 1: return osVersion;
    case 2: return appVersion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceModel = value$ != null ? value$.toString() : null; break;
    case 1: osVersion = value$ != null ? value$.toString() : null; break;
    case 2: appVersion = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceModel' field.
   * @return Device model information
   */
  public java.lang.String getDeviceModel() {
    return deviceModel;
  }


  /**
   * Sets the value of the 'deviceModel' field.
   * Device model information
   * @param value the value to set.
   */
  public void setDeviceModel(java.lang.String value) {
    this.deviceModel = value;
  }

  /**
   * Gets the value of the 'osVersion' field.
   * @return Operating system version
   */
  public java.lang.String getOsVersion() {
    return osVersion;
  }


  /**
   * Sets the value of the 'osVersion' field.
   * Operating system version
   * @param value the value to set.
   */
  public void setOsVersion(java.lang.String value) {
    this.osVersion = value;
  }

  /**
   * Gets the value of the 'appVersion' field.
   * @return Application version
   */
  public java.lang.String getAppVersion() {
    return appVersion;
  }


  /**
   * Sets the value of the 'appVersion' field.
   * Application version
   * @param value the value to set.
   */
  public void setAppVersion(java.lang.String value) {
    this.appVersion = value;
  }

  /**
   * Creates a new ClientInfo RecordBuilder.
   * @return A new ClientInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder newBuilder() {
    return new pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder();
  }

  /**
   * Creates a new ClientInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClientInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder(other);
    }
  }

  /**
   * Creates a new ClientInfo RecordBuilder by copying an existing ClientInfo instance.
   * @param other The existing instance to copy.
   * @return A new ClientInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.ClientInfo other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClientInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientInfo>
    implements org.apache.avro.data.RecordBuilder<ClientInfo> {

    /** Device model information */
    private java.lang.String deviceModel;
    /** Operating system version */
    private java.lang.String osVersion;
    /** Application version */
    private java.lang.String appVersion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceModel)) {
        this.deviceModel = data().deepCopy(fields()[0].schema(), other.deviceModel);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[1].schema(), other.osVersion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.appVersion)) {
        this.appVersion = data().deepCopy(fields()[2].schema(), other.appVersion);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ClientInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.ClientInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deviceModel)) {
        this.deviceModel = data().deepCopy(fields()[0].schema(), other.deviceModel);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[1].schema(), other.osVersion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.appVersion)) {
        this.appVersion = data().deepCopy(fields()[2].schema(), other.appVersion);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'deviceModel' field.
      * Device model information
      * @return The value.
      */
    public java.lang.String getDeviceModel() {
      return deviceModel;
    }


    /**
      * Sets the value of the 'deviceModel' field.
      * Device model information
      * @param value The value of 'deviceModel'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder setDeviceModel(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceModel = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceModel' field has been set.
      * Device model information
      * @return True if the 'deviceModel' field has been set, false otherwise.
      */
    public boolean hasDeviceModel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceModel' field.
      * Device model information
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder clearDeviceModel() {
      deviceModel = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'osVersion' field.
      * Operating system version
      * @return The value.
      */
    public java.lang.String getOsVersion() {
      return osVersion;
    }


    /**
      * Sets the value of the 'osVersion' field.
      * Operating system version
      * @param value The value of 'osVersion'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder setOsVersion(java.lang.String value) {
      validate(fields()[1], value);
      this.osVersion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'osVersion' field has been set.
      * Operating system version
      * @return True if the 'osVersion' field has been set, false otherwise.
      */
    public boolean hasOsVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'osVersion' field.
      * Operating system version
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder clearOsVersion() {
      osVersion = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'appVersion' field.
      * Application version
      * @return The value.
      */
    public java.lang.String getAppVersion() {
      return appVersion;
    }


    /**
      * Sets the value of the 'appVersion' field.
      * Application version
      * @param value The value of 'appVersion'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder setAppVersion(java.lang.String value) {
      validate(fields()[2], value);
      this.appVersion = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'appVersion' field has been set.
      * Application version
      * @return True if the 'appVersion' field has been set, false otherwise.
      */
    public boolean hasAppVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'appVersion' field.
      * Application version
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.ClientInfo.Builder clearAppVersion() {
      appVersion = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClientInfo build() {
      try {
        ClientInfo record = new ClientInfo();
        record.deviceModel = fieldSetFlags()[0] ? this.deviceModel : (java.lang.String) defaultValue(fields()[0]);
        record.osVersion = fieldSetFlags()[1] ? this.osVersion : (java.lang.String) defaultValue(fields()[1]);
        record.appVersion = fieldSetFlags()[2] ? this.appVersion : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClientInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClientInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClientInfo>
    READER$ = (org.apache.avro.io.DatumReader<ClientInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.deviceModel == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceModel);
    }

    if (this.osVersion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.osVersion);
    }

    if (this.appVersion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.appVersion);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceModel = null;
      } else {
        this.deviceModel = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.osVersion = null;
      } else {
        this.osVersion = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.appVersion = null;
      } else {
        this.appVersion = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceModel = null;
          } else {
            this.deviceModel = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.osVersion = null;
          } else {
            this.osVersion = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.appVersion = null;
          } else {
            this.appVersion = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (deviceModel == null ? 0 : deviceModel.hashCode());
    result = 31 * result + (osVersion == null ? 0 : osVersion.hashCode());
    result = 31 * result + (appVersion == null ? 0 : appVersion.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ClientInfo)) {
      return false;
    }
    ClientInfo other = (ClientInfo) o;
    if (!java.util.Objects.equals(this.deviceModel, other.deviceModel)) {
      return false;
    }
    if (!java.util.Objects.equals(this.osVersion, other.osVersion)) {
      return false;
    }
    if (!java.util.Objects.equals(this.appVersion, other.appVersion)) {
      return false;
    }
    return true;
  }
}










