/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pt.ulusofona.digital.wallet.domain.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Institution information */
@org.apache.avro.specific.AvroGenerated
public class InstitutionInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9028172283539737284L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InstitutionInfo\",\"namespace\":\"pt.ulusofona.digital.wallet.domain.avro\",\"doc\":\"Institution information\",\"fields\":[{\"name\":\"institutionCode\",\"type\":\"int\",\"doc\":\"Institution code\"},{\"name\":\"institutionName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Institution name\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InstitutionInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InstitutionInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InstitutionInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InstitutionInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InstitutionInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InstitutionInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InstitutionInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InstitutionInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InstitutionInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Institution code */
  private int institutionCode;
  /** Institution name */
  private java.lang.String institutionName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InstitutionInfo() {}

  /**
   * All-args constructor.
   * @param institutionCode Institution code
   * @param institutionName Institution name
   */
  public InstitutionInfo(java.lang.Integer institutionCode, java.lang.String institutionName) {
    this.institutionCode = institutionCode;
    this.institutionName = institutionName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return institutionCode;
    case 1: return institutionName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: institutionCode = (java.lang.Integer)value$; break;
    case 1: institutionName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'institutionCode' field.
   * @return Institution code
   */
  public int getInstitutionCode() {
    return institutionCode;
  }


  /**
   * Sets the value of the 'institutionCode' field.
   * Institution code
   * @param value the value to set.
   */
  public void setInstitutionCode(int value) {
    this.institutionCode = value;
  }

  /**
   * Gets the value of the 'institutionName' field.
   * @return Institution name
   */
  public java.lang.String getInstitutionName() {
    return institutionName;
  }


  /**
   * Sets the value of the 'institutionName' field.
   * Institution name
   * @param value the value to set.
   */
  public void setInstitutionName(java.lang.String value) {
    this.institutionName = value;
  }

  /**
   * Creates a new InstitutionInfo RecordBuilder.
   * @return A new InstitutionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder newBuilder() {
    return new pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder();
  }

  /**
   * Creates a new InstitutionInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InstitutionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder(other);
    }
  }

  /**
   * Creates a new InstitutionInfo RecordBuilder by copying an existing InstitutionInfo instance.
   * @param other The existing instance to copy.
   * @return A new InstitutionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for InstitutionInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InstitutionInfo>
    implements org.apache.avro.data.RecordBuilder<InstitutionInfo> {

    /** Institution code */
    private int institutionCode;
    /** Institution name */
    private java.lang.String institutionName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.institutionCode)) {
        this.institutionCode = data().deepCopy(fields()[0].schema(), other.institutionCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.institutionName)) {
        this.institutionName = data().deepCopy(fields()[1].schema(), other.institutionName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing InstitutionInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.institutionCode)) {
        this.institutionCode = data().deepCopy(fields()[0].schema(), other.institutionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.institutionName)) {
        this.institutionName = data().deepCopy(fields()[1].schema(), other.institutionName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'institutionCode' field.
      * Institution code
      * @return The value.
      */
    public int getInstitutionCode() {
      return institutionCode;
    }


    /**
      * Sets the value of the 'institutionCode' field.
      * Institution code
      * @param value The value of 'institutionCode'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder setInstitutionCode(int value) {
      validate(fields()[0], value);
      this.institutionCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'institutionCode' field has been set.
      * Institution code
      * @return True if the 'institutionCode' field has been set, false otherwise.
      */
    public boolean hasInstitutionCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'institutionCode' field.
      * Institution code
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder clearInstitutionCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'institutionName' field.
      * Institution name
      * @return The value.
      */
    public java.lang.String getInstitutionName() {
      return institutionName;
    }


    /**
      * Sets the value of the 'institutionName' field.
      * Institution name
      * @param value The value of 'institutionName'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder setInstitutionName(java.lang.String value) {
      validate(fields()[1], value);
      this.institutionName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'institutionName' field has been set.
      * Institution name
      * @return True if the 'institutionName' field has been set, false otherwise.
      */
    public boolean hasInstitutionName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'institutionName' field.
      * Institution name
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.InstitutionInfo.Builder clearInstitutionName() {
      institutionName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InstitutionInfo build() {
      try {
        InstitutionInfo record = new InstitutionInfo();
        record.institutionCode = fieldSetFlags()[0] ? this.institutionCode : (java.lang.Integer) defaultValue(fields()[0]);
        record.institutionName = fieldSetFlags()[1] ? this.institutionName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InstitutionInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<InstitutionInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InstitutionInfo>
    READER$ = (org.apache.avro.io.DatumReader<InstitutionInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.institutionCode);

    out.writeString(this.institutionName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.institutionCode = in.readInt();

      this.institutionName = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.institutionCode = in.readInt();
          break;

        case 1:
          this.institutionName = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Integer.hashCode(institutionCode);
    result = 31 * result + (institutionName == null ? 0 : institutionName.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof InstitutionInfo)) {
      return false;
    }
    InstitutionInfo other = (InstitutionInfo) o;
    if (this.institutionCode != other.institutionCode) {
      return false;
    }
    if (!java.util.Objects.equals(this.institutionName, other.institutionName)) {
      return false;
    }
    return true;
  }
}










