/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pt.ulusofona.digital.wallet.domain.avro;
/** Supported client platforms */
@org.apache.avro.specific.AvroGenerated
public enum PlatformType implements org.apache.avro.generic.GenericEnumSymbol<PlatformType> {
  ios, android, web, desktop  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PlatformType\",\"namespace\":\"pt.ulusofona.digital.wallet.domain.avro\",\"doc\":\"Supported client platforms\",\"symbols\":[\"ios\",\"android\",\"web\",\"desktop\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
