/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pt.ulusofona.digital.wallet.domain.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Session information for login/logout events */
@org.apache.avro.specific.AvroGenerated
public class SessionInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 167375919663132605L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SessionInfo\",\"namespace\":\"pt.ulusofona.digital.wallet.domain.avro\",\"doc\":\"Session information for login/logout events\",\"fields\":[{\"name\":\"sessionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Session identifier\"},{\"name\":\"ipAddress\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"IP address of the client\",\"default\":null},{\"name\":\"userAgent\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"User agent string\",\"default\":null},{\"name\":\"deviceInfo\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Device information\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SessionInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SessionInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SessionInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SessionInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SessionInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SessionInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SessionInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SessionInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SessionInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Session identifier */
  private java.lang.String sessionId;
  /** IP address of the client */
  private java.lang.String ipAddress;
  /** User agent string */
  private java.lang.String userAgent;
  /** Device information */
  private java.lang.String deviceInfo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SessionInfo() {}

  /**
   * All-args constructor.
   * @param sessionId Session identifier
   * @param ipAddress IP address of the client
   * @param userAgent User agent string
   * @param deviceInfo Device information
   */
  public SessionInfo(java.lang.String sessionId, java.lang.String ipAddress, java.lang.String userAgent, java.lang.String deviceInfo) {
    this.sessionId = sessionId;
    this.ipAddress = ipAddress;
    this.userAgent = userAgent;
    this.deviceInfo = deviceInfo;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionId;
    case 1: return ipAddress;
    case 2: return userAgent;
    case 3: return deviceInfo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionId = value$ != null ? value$.toString() : null; break;
    case 1: ipAddress = value$ != null ? value$.toString() : null; break;
    case 2: userAgent = value$ != null ? value$.toString() : null; break;
    case 3: deviceInfo = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sessionId' field.
   * @return Session identifier
   */
  public java.lang.String getSessionId() {
    return sessionId;
  }


  /**
   * Sets the value of the 'sessionId' field.
   * Session identifier
   * @param value the value to set.
   */
  public void setSessionId(java.lang.String value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return IP address of the client
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * IP address of the client
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'userAgent' field.
   * @return User agent string
   */
  public java.lang.String getUserAgent() {
    return userAgent;
  }


  /**
   * Sets the value of the 'userAgent' field.
   * User agent string
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.String value) {
    this.userAgent = value;
  }

  /**
   * Gets the value of the 'deviceInfo' field.
   * @return Device information
   */
  public java.lang.String getDeviceInfo() {
    return deviceInfo;
  }


  /**
   * Sets the value of the 'deviceInfo' field.
   * Device information
   * @param value the value to set.
   */
  public void setDeviceInfo(java.lang.String value) {
    this.deviceInfo = value;
  }

  /**
   * Creates a new SessionInfo RecordBuilder.
   * @return A new SessionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder newBuilder() {
    return new pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder();
  }

  /**
   * Creates a new SessionInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SessionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder(other);
    }
  }

  /**
   * Creates a new SessionInfo RecordBuilder by copying an existing SessionInfo instance.
   * @param other The existing instance to copy.
   * @return A new SessionInfo RecordBuilder
   */
  public static pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder newBuilder(pt.ulusofona.digital.wallet.domain.avro.SessionInfo other) {
    if (other == null) {
      return new pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder();
    } else {
      return new pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for SessionInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SessionInfo>
    implements org.apache.avro.data.RecordBuilder<SessionInfo> {

    /** Session identifier */
    private java.lang.String sessionId;
    /** IP address of the client */
    private java.lang.String ipAddress;
    /** User agent string */
    private java.lang.String userAgent;
    /** Device information */
    private java.lang.String deviceInfo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[1].schema(), other.ipAddress);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[2].schema(), other.userAgent);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.deviceInfo)) {
        this.deviceInfo = data().deepCopy(fields()[3].schema(), other.deviceInfo);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SessionInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(pt.ulusofona.digital.wallet.domain.avro.SessionInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[1].schema(), other.ipAddress);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[2].schema(), other.userAgent);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.deviceInfo)) {
        this.deviceInfo = data().deepCopy(fields()[3].schema(), other.deviceInfo);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'sessionId' field.
      * Session identifier
      * @return The value.
      */
    public java.lang.String getSessionId() {
      return sessionId;
    }


    /**
      * Sets the value of the 'sessionId' field.
      * Session identifier
      * @param value The value of 'sessionId'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder setSessionId(java.lang.String value) {
      validate(fields()[0], value);
      this.sessionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionId' field has been set.
      * Session identifier
      * @return True if the 'sessionId' field has been set, false otherwise.
      */
    public boolean hasSessionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sessionId' field.
      * Session identifier
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * IP address of the client
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * IP address of the client
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder setIpAddress(java.lang.String value) {
      validate(fields()[1], value);
      this.ipAddress = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * IP address of the client
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * IP address of the client
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userAgent' field.
      * User agent string
      * @return The value.
      */
    public java.lang.String getUserAgent() {
      return userAgent;
    }


    /**
      * Sets the value of the 'userAgent' field.
      * User agent string
      * @param value The value of 'userAgent'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder setUserAgent(java.lang.String value) {
      validate(fields()[2], value);
      this.userAgent = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userAgent' field has been set.
      * User agent string
      * @return True if the 'userAgent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userAgent' field.
      * User agent string
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder clearUserAgent() {
      userAgent = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceInfo' field.
      * Device information
      * @return The value.
      */
    public java.lang.String getDeviceInfo() {
      return deviceInfo;
    }


    /**
      * Sets the value of the 'deviceInfo' field.
      * Device information
      * @param value The value of 'deviceInfo'.
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder setDeviceInfo(java.lang.String value) {
      validate(fields()[3], value);
      this.deviceInfo = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceInfo' field has been set.
      * Device information
      * @return True if the 'deviceInfo' field has been set, false otherwise.
      */
    public boolean hasDeviceInfo() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'deviceInfo' field.
      * Device information
      * @return This builder.
      */
    public pt.ulusofona.digital.wallet.domain.avro.SessionInfo.Builder clearDeviceInfo() {
      deviceInfo = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SessionInfo build() {
      try {
        SessionInfo record = new SessionInfo();
        record.sessionId = fieldSetFlags()[0] ? this.sessionId : (java.lang.String) defaultValue(fields()[0]);
        record.ipAddress = fieldSetFlags()[1] ? this.ipAddress : (java.lang.String) defaultValue(fields()[1]);
        record.userAgent = fieldSetFlags()[2] ? this.userAgent : (java.lang.String) defaultValue(fields()[2]);
        record.deviceInfo = fieldSetFlags()[3] ? this.deviceInfo : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SessionInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<SessionInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SessionInfo>
    READER$ = (org.apache.avro.io.DatumReader<SessionInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sessionId);

    if (this.ipAddress == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ipAddress);
    }

    if (this.userAgent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.userAgent);
    }

    if (this.deviceInfo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceInfo);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sessionId = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.ipAddress = null;
      } else {
        this.ipAddress = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.userAgent = null;
      } else {
        this.userAgent = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceInfo = null;
      } else {
        this.deviceInfo = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sessionId = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ipAddress = null;
          } else {
            this.ipAddress = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.userAgent = null;
          } else {
            this.userAgent = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceInfo = null;
          } else {
            this.deviceInfo = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (sessionId == null ? 0 : sessionId.hashCode());
    result = 31 * result + (ipAddress == null ? 0 : ipAddress.hashCode());
    result = 31 * result + (userAgent == null ? 0 : userAgent.hashCode());
    result = 31 * result + (deviceInfo == null ? 0 : deviceInfo.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof SessionInfo)) {
      return false;
    }
    SessionInfo other = (SessionInfo) o;
    if (!java.util.Objects.equals(this.sessionId, other.sessionId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.ipAddress, other.ipAddress)) {
      return false;
    }
    if (!java.util.Objects.equals(this.userAgent, other.userAgent)) {
      return false;
    }
    if (!java.util.Objects.equals(this.deviceInfo, other.deviceInfo)) {
      return false;
    }
    return true;
  }
}










