/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pt.ulusofona.digital.wallet.domain.avro;
/** Type of student event */
@org.apache.avro.specific.AvroGenerated
public enum StudentEventType implements org.apache.avro.generic.GenericEnumSymbol<StudentEventType> {
  STUDENT_REGISTERED, STUDENT_UPDATED, STUDENT_LOGIN, STUDENT_LOGOUT, STUDENT_DELETED, STUDENT_GRADUATED, STUDENT_SUSPENDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StudentEventType\",\"namespace\":\"pt.ulusofona.digital.wallet.domain.avro\",\"doc\":\"Type of student event\",\"symbols\":[\"STUDENT_REGISTERED\",\"STUDENT_UPDATED\",\"STUDENT_LOGIN\",\"STUDENT_LOGOUT\",\"STUDENT_DELETED\",\"STUDENT_GRADUATED\",\"STUDENT_SUSPENDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
